version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: medically_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: medically_db
      MYSQL_USER: medically_user
      MYSQL_PASSWORD: medically_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - medically_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medically_app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - medically_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  medically_network:
    driver: bridge 